spring:
  h2:
    console:
      enabled: true
  database:
    platform: h2
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: sa
    password:
  mvc:
    view:
      suffix: .jsp

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 8a6eb4646a66e8c6cb22
            clientSecret: a30c695aa9cd1ecbd49a7c2a0fc6e6199b3e5996

cake:
  url: https://gist.githubusercontent.com/hart88/198f29ec5114a3ec3460/raw/8dd19a88f9b8d24c23d9960f3300d0c917a4f07c/cake.json
server:
  session:
    tracking-modes: cookie